### ISSUE TITLE
Build workflows fail on ixbrl-viewer build (webpack)

### ISSUE THREAD

**Issue by aaroncameron-wk** [Arelle/Arelle#457]
### What happened?

Workflow builds, at least Windows ([example](https://github.com/Arelle/Arelle/actions/runs/3340072843/jobs/5529763223)) and Mac (on personal fork), fail while npm builds ixbrl-viewer

Relevant logs:
```
> webpack --config iXBRLViewerPlugin/viewer/webpack.prod.js

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\webpack\lib\NormalModule.js:[41](https://github.com/Arelle/Arelle/actions/runs/3340072843/jobs/5529763223#step:10:42)7:16)
    at handleParseError (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\webpack\lib\NormalModule.js:[47](https://github.com/Arelle/Arelle/actions/runs/3340072843/jobs/5529763223#step:10:48)1:10)
    at D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\webpack\lib\NormalModule.js:[50](https://github.com/Arelle/Arelle/actions/runs/3340072843/jobs/5529763223#step:10:51)3:5
    at D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:[55](https://github.com/Arelle/Arelle/actions/runs/3340072843/jobs/5529763223#step:10:56):16)
    at D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\a\Arelle\Arelle\ixbrl-viewer\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

### Interface

Python library (pip install)

### Version

8960ed7a149c28a507c65b2e7dbd6d15b5c8bc87

### Download

From source (git checkout)

### Operating System

macOS 12 Monterey, Windows 11

**Comment by aaroncameron-wk** [comment]
Example failure pulled node version `18.12.0`, whereas previous builds and a test build with the version explicitly set used `16.17.1` successfully.

Node [released](https://github.com/nodejs/node/releases/tag/v18.12.0) LTS version `18.12.0` two days ago (2022-10-25). We may want to consider pinning the default node version to a `16.*` LTS version for the short term.

@austinmatherne-wk thoughts?

**Comment by austinmatherne-wk** [comment]
We should pin (I'll open a PR) and also get ixbrl-viewer updated to work with node 18.
