### ISSUE TITLE
Running as non-root in Kubernetes, Permission denied: '/.config'

### ISSUE THREAD

**Issue by vivet** [Arelle/Arelle#509]
### What should we change and why?

When specifying runAsNonRoot in the security-context of Kubernetes template, we get the following error:
```
Traceback (most recent call last):
   File "/home/parallels/Python39/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 74, in run
   File "/home/parallels/Python39/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
   File "arelleCmdLine.py", line 22, in <module>
   File "/media/psf/arelle/devpub/arelle/CntlrCmdLine.py", line 47, in main
   File "/media/psf/arelle/devpub/arelle/CntlrCmdLine.py", line 60, in parseAndRun
   File "/media/psf/arelle/devpub/arelle/CntlrCmdLine.py", line 533, in __init__
   File "/media/psf/arelle/devpub/arelle/Cntlr.py", line 221, in __init__
   File "/home/parallels/Python39/lib/python3.9/os.py", line 215, in makedirs
   File "/home/parallels/Python39/lib/python3.9/os.py", line 225, in makedirs
 PermissionError: [Errno 13] Permission denied: '/.config'
```

I am wondering why Arelle needs to write to the disk.
Do you have any advice of how to run Arelle without having to have root permissions, or is it something that you can change?

**Comment by austinmatherne-wk** [comment]
Hi Michael,

Can you provide the traceback with the latest version of Arelle?

**Comment by vivet** [comment]
We are using the latest version back from August. Is there a newer version?

**Comment by austinmatherne-wk** [comment]
Yes. There have been quite a few [releases](https://github.com/Arelle/Arelle/releases) since August.

**Comment by vivet** [comment]
Okay, I will ask my developer again.

**Comment by vivet** [comment]
I updated to latest version
I get the same error, just different line numbers

Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/cx_Freeze/initscripts/__startup__.py", line 138, in run
   File "/usr/local/lib/python3.10/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
   File "arelleCmdLine.py", line 20, in <module>
   File "/build/arelle/CntlrCmdLine.py", line 48, in main
   File "/build/arelle/CntlrCmdLine.py", line 72, in parseAndRun
   File "/build/arelle/CntlrCmdLine.py", line 551, in __init__
   File "/build/arelle/Cntlr.py", line 252, in __init__
   File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
 PermissionError: [Errno 13] Permission denied: '/.config'

**Comment by austinmatherne-wk** [comment]
It's attempting to create the config directory and file. There's some legacy handling for GAE that we could update to provide a CLI option to disable reading and writing the config to disk, but you'll still need to support loading/downloading XBRL files to a cache directory. Are you running Arelle in offline mode with a volume mounted HTTP cache?

**Comment by vivet** [comment]
Yes that would be great.
We are running in offline mode, and have all taxonomies stored externally. 
We also handle the output file, so I think it's just the config that causes the issue

**Comment by vivet** [comment]
Any ETA for the fix?

**Comment by austinmatherne-wk** [comment]
Hi @vivet,

Our team groomed the ticket for this today. It should be worked soon

**Comment by vivet** [comment]
Any update?

**Comment by austinmatherne-wk** [comment]
This is on our board, but we did have to pull in a few higher priority tickets. This should still be worked soon

**Comment by vivet** [comment]
Any update?

**Comment by austinmatherne-wk** [comment]
Sorry, not yet. We'll get it worked soon

**Comment by austinmatherne-wk** [comment]
Hi @vivet,

To completely avoid disk write access there are two options you'll need to use `--disablePersistentConfig` (to avoid writing config files to disk) and  `--internetConnectivity=offline` (to avoid downloading new taxonomy files to disk). Can you try using both of those and let us know if the issue persists?

**Comment by vivet** [comment]
Thanks Austtin.
We always use the offline settings, I will check my usage of the other parameter and see if I did something wrong
